spring.application.name=geotraker

spring.datasource.url=jdbc:postgresql://localhost:5432/geotrackerdb
spring.datasource.username=geotracker
spring.datasource.password=geotracker
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true